"""initial

Revision ID: 0cca3205be89
Revises: 
Create Date: 2025-12-17 08:59:41.984507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cca3205be89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS flashcards')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oauth_provider', sa.String(), nullable=True),
    sa.Column('oauth_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_id'),
    schema='flashcards'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True, schema='flashcards')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True, schema='flashcards')
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['flashcards.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='flashcards'
    )
    op.create_index(op.f('ix_decks_id'), 'decks', ['id'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_decks_owner_id'), 'decks', ['owner_id'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_decks_title'), 'decks', ['title'], unique=False, schema='flashcards')
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('next_review', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcards.decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='flashcards'
    )
    op.create_index(op.f('ix_cards_deck_id'), 'cards', ['deck_id'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False, schema='flashcards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_id'), table_name='cards', schema='flashcards')
    op.drop_index(op.f('ix_cards_deck_id'), table_name='cards', schema='flashcards')
    op.drop_table('cards', schema='flashcards')
    op.drop_index(op.f('ix_decks_title'), table_name='decks', schema='flashcards')
    op.drop_index(op.f('ix_decks_owner_id'), table_name='decks', schema='flashcards')
    op.drop_index(op.f('ix_decks_id'), table_name='decks', schema='flashcards')
    op.drop_table('decks', schema='flashcards')
    op.drop_index(op.f('ix_users_username'), table_name='users', schema='flashcards')
    op.drop_index(op.f('ix_users_id'), table_name='users', schema='flashcards')
    op.drop_index(op.f('ix_users_email'), table_name='users', schema='flashcards')
    op.drop_table('users', schema='flashcards')
    op.execute('DROP SCHEMA IF EXISTS flashcards')
    # ### end Alembic commands ###

