"""initial_migration

Revision ID: fe725562c44b
Revises: 
Create Date: 2025-12-30 21:05:22.096126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe725562c44b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oauth_provider', sa.String(), nullable=True),
    sa.Column('oauth_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_id'),
    schema='flashcards'
    )
    op.create_index(op.f('ix_flashcards_users_email'), 'users', ['email'], unique=True, schema='flashcards')
    op.create_index(op.f('ix_flashcards_users_id'), 'users', ['id'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_flashcards_users_username'), 'users', ['username'], unique=True, schema='flashcards')
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['flashcards.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='flashcards'
    )
    op.create_index(op.f('ix_flashcards_decks_id'), 'decks', ['id'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_flashcards_decks_owner_id'), 'decks', ['owner_id'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_flashcards_decks_title'), 'decks', ['title'], unique=False, schema='flashcards')
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('font_size', sa.String(), nullable=True),
    sa.Column('study_session_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['flashcards.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='flashcards'
    )
    op.create_index(op.f('ix_flashcards_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False, schema='flashcards')
    op.create_table('user_streaks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_session_streak', sa.Integer(), nullable=True),
    sa.Column('daily_streak', sa.Integer(), nullable=True),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('last_session_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['flashcards.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id', name='uq_user_streaks_user_id'),
    schema='flashcards'
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('next_review', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcards.decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='flashcards'
    )
    op.create_index(op.f('ix_flashcards_cards_deck_id'), 'cards', ['deck_id'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_flashcards_cards_id'), 'cards', ['id'], unique=False, schema='flashcards')
    op.create_table('card_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['flashcards.cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='flashcards'
    )
    op.create_index(op.f('ix_flashcards_card_options_card_id'), 'card_options', ['card_id'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_flashcards_card_options_id'), 'card_options', ['id'], unique=False, schema='flashcards')
    op.create_table('flashcard_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('sm2_quality', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['flashcards.cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['flashcards.card_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['flashcards.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='flashcards'
    )
    op.create_index(op.f('ix_flashcards_flashcard_reviews_card_id'), 'flashcard_reviews', ['card_id'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_flashcards_flashcard_reviews_id'), 'flashcard_reviews', ['id'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_flashcards_flashcard_reviews_timestamp'), 'flashcard_reviews', ['timestamp'], unique=False, schema='flashcards')
    op.create_index(op.f('ix_flashcards_flashcard_reviews_user_id'), 'flashcard_reviews', ['user_id'], unique=False, schema='flashcards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flashcards_flashcard_reviews_user_id'), table_name='flashcard_reviews', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_flashcard_reviews_timestamp'), table_name='flashcard_reviews', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_flashcard_reviews_id'), table_name='flashcard_reviews', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_flashcard_reviews_card_id'), table_name='flashcard_reviews', schema='flashcards')
    op.drop_table('flashcard_reviews', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_card_options_id'), table_name='card_options', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_card_options_card_id'), table_name='card_options', schema='flashcards')
    op.drop_table('card_options', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_cards_id'), table_name='cards', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_cards_deck_id'), table_name='cards', schema='flashcards')
    op.drop_table('cards', schema='flashcards')
    op.drop_table('user_streaks', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_user_preferences_user_id'), table_name='user_preferences', schema='flashcards')
    op.drop_table('user_preferences', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_decks_title'), table_name='decks', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_decks_owner_id'), table_name='decks', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_decks_id'), table_name='decks', schema='flashcards')
    op.drop_table('decks', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_users_username'), table_name='users', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_users_id'), table_name='users', schema='flashcards')
    op.drop_index(op.f('ix_flashcards_users_email'), table_name='users', schema='flashcards')
    op.drop_table('users', schema='flashcards')
    # ### end Alembic commands ###

